package com.modernjava.records;

import java.math.BigDecimal;
import java.util.Objects;

public record Product(String name,
                      BigDecimal cost,
                      String type) {
    //By default, the constructors that are generated by the compiler
    // are called canonical constructor.

    public Product {
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("name is not valid!");
        }
        if (cost == null || cost.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("cost is not valid!");
        }
        if (type == null || type.isBlank()) {
            throw new IllegalArgumentException("type is not valid!");
        }
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Product product = (Product) o;
        return Objects.equals(name, product.name)
                /*&& Objects.equals(type, product.type)*/
                && Objects.equals(cost, product.cost);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, cost, type);
    }
}
